
import csv

civ_prog_objects = open("../civ_prog_objects.csv", "r")
prog_objects_for_lua = open("prog_objects_for_lua.h", "w")

header_comment = """
/* This file is generated by generate_prog_objects_for_lua.py. Its purpose is to be included into injected_code.c to produce a list associating Civ 3
 * and C3X function names with addresses at runtime.
 */
"""
prog_objects_for_lua.write(header_comment)

reader = csv.reader(civ_prog_objects, delimiter=",", quotechar="\"")
for row in list(reader)[1:100]:
    job    = row[0].strip(" \"\t")
    name   = row[4].strip(" \"\t")
    c_type = (",".join(row[5:])).strip(" \"\t")

    if (job == "define" or job == "inlead" or job == "repl vptr") and any([x in c_type for x in ["__fastcall", "__thiscall", "__stdcall", "__cdecl"]]):
        lua_name = name
        injected_code_name = "patch_" + name if job == "inlead" else name
        prog_objects_for_lua.write(f"{{ \"{lua_name}\", (FARPROC){injected_code_name} }},\n")

prog_objects_for_lua.close()
civ_prog_objects.close()
